export const counties = [
  { value: 'ABD', label: 'Aberdeenshire' },
  { value: 'ANS', label: 'Angus' },
  { value: 'ARY', label: 'Argyll and Bute' },
  { value: 'AVN', label: 'Avon' },
  { value: 'BDF', label: 'Bedfordshire' },
  { value: 'BGO', label: 'Blaenau Gwent' },
  { value: 'BKM', label: 'Buckinghamshire' },
  { value: 'BNE', label: 'Berkshire' },
  { value: 'BNS', label: 'Barnsley' },
  { value: 'BOL', label: 'Bolton' },
  { value: 'BPL', label: 'Blackpool' },
  { value: 'BRC', label: 'Bracknell Forest' },
  { value: 'BRY', label: 'Bromley' },
  { value: 'BST', label: 'Bristol' },
  { value: 'BUR', label: 'Bury' },
  { value: 'CAL', label: 'Calderdale' },
  { value: 'CAM', label: 'Cambridgeshire' },
  { value: 'CMN', label: 'Carmarthenshire' },
  { value: 'CGN', label: 'Ceredigion' },
  { value: 'CGV', label: 'Craigavon' },
  { value: 'CHE', label: 'Cheshire' },
  { value: 'CKF', label: 'Carrickfergus' },
  { value: 'CKT', label: 'Cookstown' },
  { value: 'CLD', label: 'Clwyd' },
  { value: 'CLK', label: 'Clackmannanshire' },
  { value: 'CLR', label: 'Coleraine' },
  { value: 'CMA', label: 'Cumbria' },
  { value: 'CMD', label: 'Camden' },
  { value: 'CON', label: 'Cornwall' },
  { value: 'COV', label: 'Coventry' },
  { value: 'CRY', label: 'Croydon' },
  { value: 'CSR', label: 'Castlereagh' },
  { value: 'CWY', label: 'Conwy' },
  { value: 'DAL', label: 'Darlington' },
  { value: 'DEN', label: 'Denbighshire' },
  { value: 'DER', label: 'Derbyshire' },
  { value: 'DEV', label: 'Devon' },
  { value: 'DGN', label: 'Dungannon' },
  { value: 'DGY', label: 'Dumfries and Galloway' },
  { value: 'DNC', label: 'Doncaster' },
  { value: 'DND', label: 'Dundee City' },
  { value: 'DOR', label: 'Dorset' },
  { value: 'DOW', label: 'Down' },
  { value: 'DRY', label: 'Derry and Strabane' },
  { value: 'DUD', label: 'Dudley' },
  { value: 'DUR', label: 'Durham' },
  { value: 'EAL', label: 'Ealing' },
  { value: 'EAY', label: 'East Ayrshire' },
  { value: 'EDH', label: 'Edinburgh, City of' },
  { value: 'EDU', label: 'East Dunbartonshire' },
  { value: 'ELN', label: 'East Lothian' },
  { value: 'ELS', label: 'Eilean Siar' },
  { value: 'ENF', label: 'Enfield' },
  { value: 'ERW', label: 'East Renfrewshire' },
  { value: 'ERY', label: 'East Riding of Yorkshire' },
  { value: 'ESS', label: 'Essex' },
  { value: 'ESX', label: 'East Sussex' },
  { value: 'FER', label: 'Fermanagh' },
  { value: 'FIF', label: 'Fife' },
  { value: 'FLN', label: 'Flintshire' },
  { value: 'GAT', label: 'Gateshead' },
  { value: 'GLG', label: 'Glasgow City' },
  { value: 'GLS', label: 'Gloucestershire' },
  { value: 'GRE', label: 'Greenwich' },
  { value: 'GWN', label: 'Gwynedd' },
  { value: 'HAL', label: 'Halton' },
  { value: 'HAM', label: 'Hampshire' },
  { value: 'HAV', label: 'Havering' },
  { value: 'HEF', label: 'Herefordshire' },
  { value: 'HIL', label: 'Hillingdon' },
  { value: 'HLD', label: 'Highland' },
  { value: 'HMF', label: 'Hammersmith and Fulham' },
  { value: 'HNS', label: 'Hounslow' },
  { value: 'HPL', label: 'Hartlepool' },
  { value: 'HRT', label: 'Hertfordshire' },
  { value: 'HRW', label: 'Harrow' },
  { value: 'HRY', label: 'Haringey' },
  { value: 'HWF', label: 'Herefordshire, County of' },
  { value: 'IOW', label: 'Isle of Wight' },
  { value: 'ISL', label: 'Islington' },
  { value: 'IVC', label: 'Inverclyde' },
  { value: 'KEC', label: 'Kensington and Chelsea' },
  { value: 'KEN', label: 'Kent' },
  { value: 'KHL', label: 'Kingston upon Hull, City of' },
  { value: 'KIR', label: 'Kirklees' },
  { value: 'KTT', label: 'Kingston upon Thames' },
  { value: 'KWL', label: 'Knowsley' },
  { value: 'LAN', label: 'Lancashire' },
  { value: 'LBC', label: 'Lisburn and Castlereagh' },
  { value: 'LBH', label: 'Lambeth' },
  { value: 'LCE', label: 'Leicester' },
  { value: 'LDS', label: 'Leeds' },
  { value: 'LEC', label: 'Leicestershire' },
  { value: 'LEW', label: 'Lewisham' },
  { value: 'LIN', label: 'Lincolnshire' },
  { value: 'LIV', label: 'Liverpool' },
  { value: 'LMV', label: 'Limavady' },
  { value: 'LND', label: 'London, City of' },
  { value: 'LRN', label: 'Larne' },
  { value: 'LSB', label: 'Lisburn' },
  { value: 'LUT', label: 'Luton' },
  { value: 'MAN', label: 'Manchester' },
  { value: 'MDB', label: 'Middlesbrough' },
  { value: 'MDW', label: 'Medway' },
  { value: 'MEA', label: 'Mid and East Antrim' },
  { value: 'MIK', label: 'Midlothian' },
  { value: 'MLN', label: 'Midlothian' },
  { value: 'MON', label: 'Monmouthshire' },
  { value: 'MRT', label: 'Merton' },
  { value: 'MRY', label: 'Moray' },
  { value: 'MTY', label: 'Merthyr Tydfil' },
  { value: 'MYL', label: 'Moyle' },
  { value: 'MYT', label: 'Milton Keynes' },
  { value: 'NAY', label: 'North Ayrshire' },
  { value: 'NBL', label: 'Northumberland' },
  { value: 'NDN', label: 'North Down' },
  { value: 'NEL', label: 'North East Lincolnshire' },
  { value: 'NET', label: 'Newcastle upon Tyne' },
  { value: 'NFK', label: 'Norfolk' },
  { value: 'NGM', label: 'Nottingham' },
  { value: 'NLK', label: 'North Lanarkshire' },
  { value: 'NLN', label: 'North Lincolnshire' },
  { value: 'NSM', label: 'North Somerset' },
  { value: 'NTH', label: 'Northamptonshire' },
  { value: 'NTL', label: 'Neath Port Talbot' },
  { value: 'NTT', label: 'Nottinghamshire' },
  { value: 'NTY', label: 'North Tyneside' },
  { value: 'NWM', label: 'Newham' },
  { value: 'NWP', label: 'Newport' },
  { value: 'NYK', label: 'North Yorkshire' },
  { value: 'NYM', label: 'Newry and Mourne' },
  { value: 'OLD', label: 'Oldham' },
  { value: 'OMH', label: 'Omagh' },
  { value: 'ORK', label: 'Orkney Islands' },
  { value: 'OXF', label: 'Oxfordshire' },
  { value: 'PEM', label: 'Pembrokeshire' },
  { value: 'PKN', label: 'Perth and Kinross' },
  { value: 'PLY', label: 'Plymouth' },
  { value: 'POL', label: 'Poole' },
  { value: 'POR', label: 'Portsmouth' },
  { value: 'POW', label: 'Powys' },
  { value: 'PTE', label: 'Peterborough' },
  { value: 'RCC', label: 'Redcar and Cleveland' },
  { value: 'RCH', label: 'Rochdale' },
  { value: 'RCT', label: 'Rhondda Cynon Taf' },
  { value: 'RDG', label: 'Reading' },
  { value: 'REN', label: 'Renfrewshire' },
  { value: 'RIC', label: 'Richmond upon Thames' },
  { value: 'ROT', label: 'Rotherham' },
  { value: 'RUT', label: 'Rutland' },
  { value: 'SAW', label: 'Sandwell' },
  { value: 'SCB', label: 'Scottish Borders, The' },
  { value: 'SFK', label: 'Suffolk' },
  { value: 'SFT', label: 'Sefton' },
  { value: 'SGC', label: 'South Gloucestershire' },
  { value: 'SHF', label: 'Sheffield' },
  { value: 'SHN', label: 'St. Helens' },
  { value: 'SHR', label: 'Shropshire' },
  { value: 'SKP', label: 'Stockport' },
  { value: 'SLF', label: 'Salford' },
  { value: 'SLG', label: 'Slough' },
  { value: 'SLK', label: 'South Lanarkshire' },
  { value: 'SND', label: 'Sunderland' },
  { value: 'SOL', label: 'Solihull' },
  { value: 'SOM', label: 'Somerset' },
  { value: 'SOS', label: 'Southend-on-Sea' },
  { value: 'SRY', label: 'Surrey' },
  { value: 'SSC', label: 'Southampton' },
  { value: 'STB', label: 'Strabane' },
  { value: 'STE', label: 'Stoke-on-Trent' },
  { value: 'STG', label: 'Stirling' },
  { value: 'STH', label: 'Southwark' },
  { value: 'STN', label: 'Sutton' },
  { value: 'STS', label: 'Staffordshire' },
  { value: 'STT', label: 'Stockton-on-Tees' },
  { value: 'STY', label: 'South Tyneside' },
  { value: 'SWA', label: 'Swansea' },
  { value: 'SWD', label: 'Swindon' },
  { value: 'TAM', label: 'Tameside' },
  { value: 'TFW', label: 'Telford and Wrekin' },
  { value: 'THR', label: 'Thurrock' },
  { value: 'TOB', label: 'Torbay' },
  { value: 'TOF', label: 'Torfaen' },
  { value: 'TRF', label: 'Trafford' },
  { value: 'TWH', label: 'Tynemouth' },
  { value: 'UKM', label: 'United Kingdom' },
  { value: 'VGL', label: 'Vale of Glamorgan, The' },
  { value: 'WKF', label: 'Wakefield' },
  { value: 'WLL', label: 'Walsall' },
  { value: 'WLN', label: 'West Lothian' },
  { value: 'WLV', label: 'Wolverhampton' },
  { value: 'WND', label: 'Wandsworth' },
  { value: 'WNM', label: 'Windsor and Maidenhead' },
  { value: 'WOK', label: 'Wokingham' },
  { value: 'WOR', label: 'Worcestershire' },
  { value: 'WRL', label: 'Wirral' },
  { value: 'WRT', label: 'Warrington' },
  { value: 'WRX', label: 'Wrexham' },
  { value: 'WSM', label: 'Westminster' },
  { value: 'WSX', label: 'West Sussex' },
  { value: 'YOR', label: 'York' }
];
